[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.0"
tag_format = "v$version"
version_files = [
    "VERSION",
    "apps/core/version.py:__version__"
]
update_changelog_on_bump = true
changelog_incremental = true
changelog_start_rev = "v0.0.0"

[tool.commitizen.customize]
message_template = "{{change_type}}{% if scope %}({{scope}}){% endif %}: {{message}}"
example = "feat(user): add email verification"
schema_pattern = "^(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(?:\\([^()]*\\))?:\\s[^\\s].*"

[tool.commitizen.customize.change_type_map]
feat = "Features"
fix = "Bug Fixes"
docs = "Documentation"
style = "Code Style"
refactor = "Code Refactoring"
perf = "Performance"
test = "Testing"
build = "Build System"
ci = "CI/CD"
chore = "Chores"
revert = "Reverts"
