site_name: Django Backend Template
nav:
    -   Overview: index.md
    -   Getting Started:
            -   Developer Setup: docs/dev_setup.md
            -   Environments: docs/environments.md
    -   Development:
            -   Contributing: docs/contributing.md
            -   Security: docs/security.md
            -   Context: docs/context.md
    -   Authentication: docs/authentication.md
theme:
    name: material
