name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.11'

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install commitizen

            -   name: Generate release notes
                run: |
                    cz changelog --unreleased-only > RELEASE_NOTES.md

            -   name: Create GitHub Release
                uses: softprops/action-gh-release@v1
                with:
                    body_path: RELEASE_NOTES.md
                    draft: false
                    prerelease: false
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
